# Generated by Django 5.0.6 on 2024-08-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consola',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='consolas/'),
        ),
        migrations.AddField(
            model_name='funko',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='funkos/'),
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perifericos/'),
        ),
    ]
